Revert "US3987 remove dependencies on jquery-migrate"
This reverts commit 122fdb519b1024d017b6bb2f0defad619d2fc1c3.

Fixes error:

Error: Mismatched anonymous define() module: undefined
http://requirejs.org/docs/errors.html#mismatc